### ISSUE TITLE
Chrome issues

### ISSUE THREAD

**Issue by shivamjaiswal64** [shivamjaiswal64/MiniOS#2]
Sometime Chrome is not invoked. There is also problem to adjust different path for 32-bit user and 64-bit user.
How to know the user's System bit and set the eligible path?

**Comment by werainkhatri** [comment]
use System.getProperty("os.arch") to know the processor version (eg amd64) and change the url accordingly

**Comment by iqueso** [comment]
> 
> 
> use System.getProperty("os.arch") to know the processor version (eg amd64) and change the url accordingly

This returns the architecture of the JRE. But I guess it depends how seriously we are taking this program lol.
